[2022-11-21T10:45:26.893+0700] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_process.save_new_raw_data_track scheduled__2022-11-18T10:00:00+00:00 [queued]>
[2022-11-21T10:45:26.912+0700] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_process.save_new_raw_data_track scheduled__2022-11-18T10:00:00+00:00 [queued]>
[2022-11-21T10:45:26.912+0700] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-21T10:45:26.913+0700] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-11-21T10:45:26.913+0700] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-21T10:45:26.965+0700] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): save_new_raw_data_track> on 2022-11-18 10:00:00+00:00
[2022-11-21T10:45:26.970+0700] {standard_task_runner.py:55} INFO - Started process 32108 to run task
[2022-11-21T10:45:26.974+0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'etl_process', 'save_new_raw_data_track', 'scheduled__2022-11-18T10:00:00+00:00', '--job-id', '151', '--raw', '--subdir', '/home/tanle/Documents/Spotify_project/airflow_spotify.py/dags/extract.py', '--cfg-path', '/tmp/tmp515rvm82']
[2022-11-21T10:45:26.976+0700] {standard_task_runner.py:83} INFO - Job 151: Subtask save_new_raw_data_track
[2022-11-21T10:45:27.216+0700] {task_command.py:376} INFO - Running <TaskInstance: etl_process.save_new_raw_data_track scheduled__2022-11-18T10:00:00+00:00 [running]> on host tanle-Precision-M4600
[2022-11-21T10:45:27.501+0700] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lexuantan2000@gmail.com
AIRFLOW_CTX_DAG_OWNER=tanle
AIRFLOW_CTX_DAG_ID=etl_process
AIRFLOW_CTX_TASK_ID=save_new_raw_data_track
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T10:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-18T10:00:00+00:00
[2022-11-21T10:45:27.507+0700] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/dags/extract.py", line 74, in save_new_raw_data_track
    for song in response['items']:
TypeError: string indices must be integers
[2022-11-21T10:45:27.602+0700] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_process, task_id=save_new_raw_data_track, execution_date=20221118T100000, start_date=20221121T034526, end_date=20221121T034527
[2022-11-21T10:45:27.675+0700] {logging_mixin.py:120} WARNING - /home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/utils/email.py:120 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-11-21T10:45:27.676+0700] {configuration.py:569} WARNING - section/key [smtp/smtp_user] not found in config
[2022-11-21T10:45:27.676+0700] {email.py:229} INFO - Email alerting: attempt 1
[2022-11-21T10:45:27.730+0700] {configuration.py:569} WARNING - section/key [smtp/smtp_user] not found in config
[2022-11-21T10:45:27.730+0700] {email.py:229} INFO - Email alerting: attempt 1
[2022-11-21T10:45:27.731+0700] {taskinstance.py:1914} ERROR - Failed to send email to: ['lexuantan2000@gmail.com']
Traceback (most recent call last):
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1603, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1664, in _execute_task
    result = execute_callable(context=context)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/dags/extract.py", line 74, in save_new_raw_data_track
    for song in response['items']:
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2315, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/utils/email.py", line 59, in send_email
    return backend(
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1912, in handle_failure
    self.email_alert(error, task)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2317, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/utils/email.py", line 59, in send_email
    return backend(
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/tanle/Documents/Spotify_project/airflow_spotify.py/env/lib/python3.10/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2022-11-21T10:45:27.797+0700] {standard_task_runner.py:100} ERROR - Failed to execute job 151 for task save_new_raw_data_track (string indices must be integers; 32108)
[2022-11-21T10:45:27.842+0700] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-21T10:45:27.872+0700] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
